### PR TITLE
Cross build with 2.12.x 2.13.x 0.6.x 1.x.x latest

### PR DESCRIPTION
**Pull request by nkgm**
Introduced `SCALAJS_VERSION` env var as in `slinky` build (tested with `0.6.33`, `1.4.0`) + conditionals for cross building
Bumped sbt to `1.4.4` (warnings in publish.sbt)
Bumped `slinky`, `scalatest` to the highest possible version (compilation errors for `0.6.6`, `3.2.x`)

Please let me know if there's anything more I can help with.

### CODE REVIEW

**Review by shadaj — APPROVED** [review]
This looks great, thanks for the PR! I'll merge it in now, but the cross-build will likely not get published since we have an old Travis build. I'll follow up shortly with a PR to switch to GitHub Actions.

**Comment by nkgm** [comment]
Thanks so much for publishing. I believe the `README` references an even older `styled-components` version (should be `4.2.0`) but this will change anyway with the new facade.

Small note, not that it makes an actual difference: 
I believe this was meant to be `0.6.33`
https://github.com/shadaj/slinky-styled-components/blob/4dc926240c176505d2e2afeebf63706d7608025c/publish.sh#L15

**Comment by shadaj** [comment]
@nkgm good catch! Scala.js version should be fixed with the next build
